// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return web;
      case TargetPlatform.windows:
        return web;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVxJ_N2suVhLQ12Jr4sjO4dGqByo1ak6U',
    appId: '1:979027959272:web:2c97c41ea884d18197d85d',
    messagingSenderId: '979027959272',
    projectId: 'mykitchenapp-5184a',
    authDomain: 'mykitchenapp-5184a.firebaseapp.com',
    storageBucket: 'mykitchenapp-5184a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDsXLlqjbesKld5ApL3tncknMighj8Y5TQ',
    appId: '1:979027959272:android:1f67cb409e2ef76897d85d',
    messagingSenderId: '979027959272',
    projectId: 'mykitchenapp-5184a',
    storageBucket: 'mykitchenapp-5184a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZdiH6dqPgQfH8zlyczF29acqLgqoP3_E',
    appId: '1:979027959272:ios:190732330747c6bf97d85d',
    messagingSenderId: '979027959272',
    projectId: 'mykitchenapp-5184a',
    storageBucket: 'mykitchenapp-5184a.firebasestorage.app',
    iosBundleId: 'com.example.mykitchenapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZdiH6dqPgQfH8zlyczF29acqLgqoP3_E',
    appId: '1:979027959272:ios:190732330747c6bf97d85d',
    messagingSenderId: '979027959272',
    projectId: 'mykitchenapp-5184a',
    storageBucket: 'mykitchenapp-5184a.firebasestorage.app',
    iosBundleId: 'com.example.mykitchenapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAVxJ_N2suVhLQ12Jr4sjO4dGqByo1ak6U',
    appId: '1:979027959272:web:f02b697234d19d5097d85d',
    messagingSenderId: '979027959272',
    projectId: 'mykitchenapp-5184a',
    authDomain: 'mykitchenapp-5184a.firebaseapp.com',
    storageBucket: 'mykitchenapp-5184a.firebasestorage.app',
  );

  //
}